### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by SUMITHSAI**
I have added an image and made the readme file look attractive and sorted. Kindly give your valuable suggestions

### CODE REVIEW

**Review by SUMITHSAI — COMMENTED** [review]
Kindly verify and merge my pr sir

**Review by industrustech — COMMENTED** [review]
Ok here by approving sumith Sai pull request after detailed review

**Comment by elwinaugustin** [comment]
@SUMITHSAI  

Hi there,

I understand that this repository is currently excluded from the Hacktoberfest 23 event, as some users have reported that it does not match the Hacktoberfest guidelines.

If you are interested in contributing to Hacktoberfest, I encourage you to check out our other Hacktoberfest-labeled repositories, or to contribute to other public Hacktoberfest-labeled repositories.

Thank you for your understanding!

**Comment by elwinaugustin** [comment]
@SUMITHSAI  

Hi there,

I understand that this repository is currently excluded from the Hacktoberfest 23 event, as some users have reported that it does not match the Hacktoberfest guidelines.

If you are interested in contributing to Hacktoberfest, I encourage you to check out our other Hacktoberfest-labeled repositories, or to contribute to other public Hacktoberfest-labeled repositories.

Thank you for your understanding!

**Pull request merged**
